name: "Pull Request Seal of Approval"
description: "Tells the developer that they may click the green “Merge pull request” button"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        SHA=${{ github.event.pull_request.head.sha }}
        DIMENSIONS="$(node -p "[1000 + parseInt('${SHA:1:5}', 16) % 24, 1000 + parseInt('${SHA:8:5}', 16) % 24].join('x')")"
        echo '{"name":"🦭","head_sha":"${{ github.event.pull_request.head.sha }}","status":"completed","conclusion":"success","output":{"title":"You can now merge this branch!","summary":"\u00a0","images":[{"alt":"🦭","image_url":"https://source.unsplash.com/'$DIMENSIONS'/?seal","caption":"Seal of approval"}]}}' | gh api -X POST '/repos/${{ github.repository }}/check-runs' --input -
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
