on:
  pull_request:
    branches: [main]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X POST '/repos/${{ github.repository }}/statuses/${{ github.sha }}' -f state=success -f description='🦭' -f context=seal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
