name: seal
on:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '{"name":"🦭","head_sha":"${{ github.sha }}","status":"completed","conclusion":"success","output":{"title":"You can now merge this branch!","summary":"Seal of approval."}}' | gh api -X POST '/repos/${{ github.repository }}/check-runs' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
