name: 🦭
on:
  pull_request:
    branches: [main]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '{"name":"🦭🦭🦭🦭🦭","head_sha":"${{ github.sha }}","status":"completed","conclusion":"success","output":{"title":"🦭🦭","summary":"🦭"}}' | gh api -X POST '/repos/${{ github.repository }}/check-runs' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
